### ISSUE TITLE
Best way to autoreload browser page

### ISSUE THREAD

**Issue by giacomocerquone** [giacomocerquone/angular4-mean-starter#1]
I found different ways to do this, but based on the experience of others, I'd like to find the most clean way to do a live reload on the target browser.

**Comment by joshwiens** [comment]
Browser sync & a watch task

**Comment by giacomocerquone** [comment]
Yes, I already thought to them. I still have some problems to integrate browsersync with nodemon. I'm about to push the changes, if you'd like to take a look you're welcome :) closing.

**Comment by joshwiens** [comment]
Assuming you want to avoid gulp ...

https://gist.github.com/sogko/b53d33d4f3b40d3b4b2e

**Comment by giacomocerquone** [comment]
I solved everything (I had already saw that gist anyway).
The problem was that in npm scripts browsersync didn't like single quotes for file watching :tired_face: 
Thank you!
