### ISSUE TITLE
Changing ports.

### ISSUE THREAD

**Issue by harisaamin** [giacomocerquone/angular4-mean-starter#2]
I'm new to development with Angular, and using this kit for a basic application. When I hit "npm start", the server starts on 8080, but the browser always points to localhost:3000. I have spent an entire day scouring the files to change the port somehow, but haven't found any port declarations in any of the package.json files. I have gone through code for nodemon and browser-sync, trying to follow and track down how I can change the port, but to no avail.

**Comment by giacomocerquone** [comment]
It is strange actually!
npm start calls browsersync's script and there is defined the 8080 port... I don't know why your browser points to 3000.
Anyway as of now I advice you to use another starter, I'm about to push some important changes and update all the stuff! I can't help you more for now! Just wait 3 days 😄

**Comment by harisaamin** [comment]
I changed to another starter kit, but would love to know if you found anything that I missed while trying to shoot down the problem! Thanks!

**Comment by giacomocerquone** [comment]
@harisaamin This starter now supports angular cli! Read the full README to know what's new.
Now to change port, you just need to edit the angular-cli.json file (here -> https://github.com/giacomocerquone/angular4-mean-starter/blob/master/.angular-cli.json#L57)

**Comment by harisaamin** [comment]
Shall go through this.. Muchos gracias!
