### ISSUE TITLE
GET http://localhost:4200/api/v1/todos 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by Arpanx** [giacomocerquone/angular4-mean-starter#3]
After "npm start" in browser console this "GET http://localhost:4200/api/v1/todos 504 (Gateway Timeout)"
And it should be like this "http://localhost:3000/api/v1/todos", because in the "Postman" alone this line works as it should.
What is the right way to start everything to work?
Thank you!

P.S if edit angular-cli.json 
```
"defaults": {
    "styleExt": "css",
    "component": {},
    "serve": {
      "port": 3000  ( <- it was 4200)
    }
  }
}
```
then I'm at the stage of compilation and start getting it
"Port 3000 is already in use. Use '--port' to specify a different port."

**Comment by giacomocerquone** [comment]
Hi, thanks for using my starter.
First of all, use the apex when you have to put code in a issue.

I tried to clone and start the project and it's all fine, I don't get any `gateway timeout`. It must be something you configured in the wrong way.

Then for the second problem it's pretty much obvious that you get "port 3000 is already in use", maybe I should document it better.
On port 3000 there is expressjs, on port 4200 there is angular. If you set angular to 3000 you have to move somewhere else expressjs.
The angular cli project is structured to be proxied by expressjs as you can see in this [file](https://github.com/giacomocerquone/angular4-mean-starter/blob/master/proxy.conf.json)

**Comment by Arpanx** [comment]
Yes, everything works. I found a mistake in myself. Port 3000 was busy (and there is no way to fix it). I changed all of the settings to 3000 at 3001.
And everything worked from the first. + Mongoose@4.12.1
Thank you for the project!

**Comment by giacomocerquone** [comment]
Seems perfect!
Ps. This starter is still updating, I'll add jwt Auth and separation of components as soon as I can
